// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etzyvutmolrqdxosekgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0enl2dXRtb2xycWR4b3Nla2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzA0NjQsImV4cCI6MjA1OTAwNjQ2NH0.GTOh9ALyK3E01qUtYY8SX7DzSYq3xq4iQyrVtSG6ocU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);